Remove Z_ERRNO from inflate
libnxz/power-gzip pull request #123
Opened 2021-12-21 14:14 UTC by lucmaga

Stop returning Z_ERRNO on inflate to align with zlib's behavior.
Two Z_ERRNO was replaced by Z_DATA_ERROR. The third error could
be suppressed, the error will be logged but the code will continue
to run.

Resolves issue #52.

2021-12-22 13:33 UTC, rzinsly approved these changes

2021-12-24 13:08 UTC, tuliom requested changes
@lucmaga Changes looks good to me, but I missed your Signed-off-by.

2021-12-27 12:46 UTC, lucmaga commented
@tuliom Fixed :)

2021-12-27 15:05 UTC, tuliom approved these changes

2021-12-27 18:22 UTC, merged