Add Copyright message for files derived from zlib.
libnxz/power-gzip pull request #131
Opened 2022-01-11 12:40 UTC by lucmaga

2022-01-11 14:05 UTC, rzinsly requested changes
lib/nx_compress.c seems to be derived from zlib's compress.c the same way lib/nx_uncompr.c is from uncompr.c.
It may be other files that need the copyright notice as well.

2022-01-11 14:05 UTC, rzinsly commented on lib/nx_uncompr.c
>  /* uncompr.c -- decompress a memory buffer
nx_uncompr.c

2022-01-12 12:17 UTC, rzinsly approved these changes

2022-01-12 12:37 UTC, mscastanho approved these changes

2022-01-12 20:53 UTC, merged